#!/usr/bin/env python3
"""flywheel — the verifier-side of the verified-NN-op flywheel.

The proposer (the Almide op body in src/<module>.almd) is written by a human/LLM.
EVERYTHING ELSE is mechanical and lives here: given a recipe (a numpy reference +
a seeded input spec), this generates a baked Almide parity test, runs it, and
reports green/red. Adding a verified op = write src/<op>.almd + a ~15-line recipe
→ `python oplab/flywheel.py <op>`.

The generated test is a pure WASM-path test (no fs, no native), so it sidesteps
the native-codegen bug almide/almide#739 while still giving an independent
float64 parity receipt — the op-level analogue of tools/compare_logits.py.

Recipe contract (oplab/recipes/<name>.py):
    NAME    = "scan_diag"              # used in test title / messages
    MODULE  = "scan"                   # src/<MODULE>.almd, imported as self.<MODULE>
    CALL    = "scan.scan_diag(a, b, x)"# Almide call; names match make_inputs keys
    TOL     = 1e-9
    SEED    = 1234
    def make_inputs(rng) -> dict[str, tuple[str, np.ndarray]]:
        # kind is "matrix" (2-D) or "vector" (1-D)
        return {"a": ("matrix", ...), "b": ("matrix", ...), "x": ("matrix", ...)}
    def reference(**arrays) -> np.ndarray:   # returns (T, D)
        ...
"""
import importlib.util
import pathlib
import subprocess
import sys

import numpy as np

OPLAB = pathlib.Path(__file__).resolve().parent
REPO = OPLAB.parent
GEN = OPLAB / "gen"
RECIPES = OPLAB / "recipes"


def alm_float(x: float) -> str:
    """Render a Python float as a syntactically valid Almide float literal
    (shortest round-trip, always carrying a decimal point)."""
    s = repr(float(x))
    if "e" in s or "E" in s:
        mant, _, exp = s.replace("E", "e").partition("e")
        if "." not in mant:
            mant += ".0"
        return f"{mant}e{exp}"
    if "." not in s:
        s += ".0"
    return s


def alm_matrix(arr: np.ndarray) -> str:
    rows = ", ".join(
        "[" + ", ".join(alm_float(x) for x in row) + "]" for row in arr
    )
    return f"matrix.from_lists([{rows}])"


def alm_vector(arr: np.ndarray) -> str:
    return "[" + ", ".join(alm_float(x) for x in arr) + "]"


def load_recipe(name: str):
    path = RECIPES / f"{name}.py"
    if not path.exists():
        sys.exit(f"no recipe: {path}")
    spec = importlib.util.spec_from_file_location(f"recipe_{name}", path)
    mod = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(mod)
    return mod


def render(recipe) -> tuple[str, int, int]:
    rng = np.random.default_rng(recipe.SEED)
    inputs = recipe.make_inputs(rng)
    arrays = {k: np.asarray(v[1], dtype=np.float64) for k, v in inputs.items()}
    y = np.asarray(recipe.reference(**arrays), dtype=np.float64)
    t, d = y.shape
    ref_flat = ", ".join(alm_float(v) for v in y.reshape(-1))

    lets = []
    for name, (kind, _) in inputs.items():
        arr = arrays[name]
        if kind == "matrix":
            lit = alm_matrix(arr)
        elif kind == "vector":
            lit = alm_vector(arr)
        else:  # scalar → plain Almide float literal
            lit = alm_float(float(arr))
        lets.append(f"  let {name} = {lit}")
    lets_src = "\n".join(lets)

    src = f"""// GENERATED by oplab/flywheel.py from oplab/recipes/{recipe.NAME}.py — do not edit.
// Independent numpy(f64) parity oracle for `{recipe.NAME}`. seed={recipe.SEED}, tol={recipe.TOL}.
// Proposer = src/{recipe.MODULE}.almd ; verifier = this generated test.
import self.{recipe.MODULE}

test "{recipe.NAME} numpy-parity (generated, seed {recipe.SEED})" {{
{lets_src}
  let y = {recipe.CALL}
  let ref = [{ref_flat}]
  var r = 0
  while r < {t} {{
    var c = 0
    while c < {d} {{
      let got = matrix.get(y, r, c)
      let want = list.get_or(ref, r * {d} + c, 0.0)
      assert(float.abs(got - want) < {alm_float(recipe.TOL)}, "{recipe.NAME} cell vs numpy")
      c = c + 1
    }}
    r = r + 1
  }}
}}
"""
    return src, t, d


def run_one(name: str) -> bool:
    recipe = load_recipe(name)
    src, t, d = render(recipe)
    GEN.mkdir(exist_ok=True)
    out = GEN / f"{name}_parity.almd"
    out.write_text(src)
    rel = out.relative_to(REPO).as_posix()
    print(f"[{name}] generated {rel}  (T={t}, D={d}, tol={recipe.TOL})")
    proc = subprocess.run(
        ["almide", "test", rel],
        cwd=REPO,
        capture_output=True,
        text=True,
    )
    tail = (proc.stdout + proc.stderr).strip().splitlines()
    ok = proc.returncode == 0 and any("passed" in l for l in tail)
    print(f"[{name}] {'PASS' if ok else 'FAIL'}")
    if not ok:
        for line in tail[-12:]:
            print("    " + line)
    return ok


def main() -> None:
    names = sys.argv[1:]
    if not names:
        names = sorted(p.stem for p in RECIPES.glob("*.py") if p.stem != "__init__")
    results = {n: run_one(n) for n in names}
    print("\n=== flywheel ===")
    for n, ok in results.items():
        print(f"  {'✓' if ok else '✗'} {n}")
    sys.exit(0 if all(results.values()) else 1)


if __name__ == "__main__":
    main()
